apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-app-python.fullname" . }}
  labels:
    {{- include "simple-app-python.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "simple-app-python.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-app-python.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP