apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "simple-app-python.fullname" . }}
  labels:
    {{- include "simple-app-python.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://"
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: {{ .Values.ingress.prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "simple-app-python.fullname" . }}
                port:
                  number: 8080
