apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-app-python.fullname" . }}
  labels:
    {{- include "simple-app-python.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple-app-python.selectorLabels" . | nindent 4 }}